### ISSUE TITLE
How to consume this service using nodejs ?

### ISSUE THREAD

**Issue by h2atecnologia** [c16a/microq#2]
how about any example (Go or NodeJS)...

**Comment by c16a** [comment]
This is simply a Websocket-based broker, so you could even start consuming it using Postman. You just need to send JSON requests to interact. The schemas can be found here. Let me know if you have any issues.

https://github.com/c16a/microq/tree/main/events

**Comment by c16a** [comment]
Closing this for now. Reopen if needed.

**Comment by h2atecnologia** [comment]
thanks for your answer.
